#!/bin/bash

if [ $LMOD_FAMILY_MPI == "cray-mpich" ]; then
  grank=$PMI_RANK
  lrank=$PMI_LOCAL_RANK
  lsize=$PMI_LOCAL_SIZE
elif [ $LMOD_FAMILY_MPI == "openmpi" ]; then
  grank=$OMPI_COMM_WORLD_RANK
  lrank=$OMPI_COMM_WORLD_LOCAL_RANK
  lsize=$OMPI_COMM_WORLD_LOCAL_SIZE
else
  >&2 echo "Error: mpibind balanced requires either cray-mpich or openmpi"
  exit 2
fi

if [[ -z "$OMP_NUM_THREADS" ]]; then 
  export OMP_NUM_THREADS=1
fi
nthds=$OMP_NUM_THREADS
nsock=`lscpu | grep Socket | awk '{print $2}'`
cpsock=`lscpu | grep "per sock" | awk '{print $4}'`
rank_per_sock=$((lsize/nsock + (lsize%nsock)))
thrd_per_sock=$((rank_per_sock*nthds))
s0ranges=()
s1ranges=()
for i in `seq 0 $nthds $((thrd_per_sock - 1))`; do
	s0ranges+=("$i-$((i+nthds-1))")
	s1ranges+=("$((i+cpsock))-$((i+cpsock+nthds-1))")
done
ranges=("${s0ranges[@]}" "${s1ranges[@]}")
echo "rank: $grank, cores: ${ranges[lrank]}" > $TMPDIR/mpibind.log.$grank.tmp
numactl -C "${ranges[lrank]}" $*
